os: linux
dist: xenial
language: shell

install:
  - sudo apt-get update
  - make build-depends

script:
  - make test

before_deploy:
    - mkdir deploy
    - mv *.csv deploy
    - mv tmp deploy

deploy:
    provider: pages
    strategy: git
    skip_cleanup: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: deploy
    on:
        branch: master
        condition: $GITHUB_TOKEN
