#!/bin/bash
#
# Get the CPL raw html files, ready for processing with the extractor
#
# TODO
# - be smarter about the pagination - dont just hardcode it

PREFIX="$1"
if [ -n "$PREFIX" ]; then
    PREFIX="$PREFIX/"
fi

set -e

curl_h() {
    local FILE="$1"
    local URL="$2"
    echo "TRY $URL"
    curl \
        -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0' \
        -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' \
        -H 'Accept-Language: en-US,en;q=0.5' \
        --compressed \
        -H 'Referer: https://cplonline.com.au/storage.html?limit=60' \
        -H 'Connection: keep-alive' \
        -H 'Cookie: frontend=a7d78ba0d87b8e06af91154683c1c077; frontend_cid=Ruatt0e3lN0l1SUG; __zlcmid=upicUqBWg7APsR' \
        -H 'Upgrade-Insecure-Requests: 1' \
        -o "$FILE" \
        "$URL"
}

(cat <<EOF
cplstorage-desk01.html https://cplonline.com.au/storage/desktop-hard-drive.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-desk02.html https://cplonline.com.au/storage/desktop-hard-drive.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-lap01.html  https://cplonline.com.au/storage/laptop-hard-drive.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-sas01.html  https://cplonline.com.au/storage/enterprise-hard-drives.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-sas02.html  https://cplonline.com.au/storage/enterprise-hard-drives.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-ssd01.html  https://cplonline.com.au/storage/ssd.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-ssd02.html  https://cplonline.com.au/storage/ssd.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-ssd03.html  https://cplonline.com.au/storage/ssd.html?dir=asc&limit=60&order=popularity&p=3
cplstorage-ssd04.html  https://cplonline.com.au/storage/ssd.html?dir=asc&limit=60&order=popularity&p=4
cplstorage-ssd05.html  https://cplonline.com.au/storage/ssd.html?dir=asc&limit=60&order=popularity&p=5
cplstorage-ext01.html  https://cplonline.com.au/storage/external-hard-drives.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-ext02.html  https://cplonline.com.au/storage/external-hard-drives.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-ext03.html  https://cplonline.com.au/storage/external-hard-drives.html?dir=asc&limit=60&order=popularity&p=3
cplstorage-ext04.html  https://cplonline.com.au/storage/external-hard-drives.html?dir=asc&limit=60&order=popularity&p=4
cplstorage-extssd.html https://cplonline.com.au/storage/external-portable-ssd.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-usb01.html  https://cplonline.com.au/storage/usb-keys.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-usb02.html  https://cplonline.com.au/storage/usb-keys.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-usb03.html  https://cplonline.com.au/storage/usb-keys.html?dir=asc&limit=60&order=popularity&p=3
cplstorage-usb04.html  https://cplonline.com.au/storage/usb-keys.html?dir=asc&limit=60&order=popularity&p=4
cplstorage-sd01.html   https://cplonline.com.au/storage/sd-card-micro-sd.html?dir=asc&limit=60&order=popularity&p=1
cplstorage-sd02.html   https://cplonline.com.au/storage/sd-card-micro-sd.html?dir=asc&limit=60&order=popularity&p=2
cplstorage-sd03.html   https://cplonline.com.au/storage/sd-card-micro-sd.html?dir=asc&limit=60&order=popularity&p=3
cplstorage-cf03.html   https://cplonline.com.au/storage/comapact-flash.html?dir=asc&limit=60&order=popularity&p=1
EOF
) | while read -r name url; do
    curl_h "$PREFIX$name" "$url"
    sleep 10s
done
