#!/bin/bash
#
# Fetch the previous published merged database
#

SLUG=hamishcoleman/scrape-storage-prices
if [ -n "$GITHUB_REPOSITORY" ]; then
    SLUG="$GITHUB_REPOSITORY"
fi

GITHUB_USER=$(echo "$SLUG" | cut -d/ -f1)
GITHUB_REPO=$(echo "$SLUG" | cut -d/ -f2)

if curl -f -o merged.csv.old "https://$GITHUB_USER.github.io/$GITHUB_REPO/merged.csv"; then
    true
else
    rm -f merged.csv.old
    touch merged.csv.old
fi
