#!/bin/bash
#
# Fetch the previous published merged database
#

GITHUB_USER=$(echo "$TRAVIS_REPO_SLUG" | cut -d/ -f1)
GITHUB_REPO=$(echo "$TRAVIS_REPO_SLUG" | cut -d/ -f2)

curl -f -o merged-old.csv "https://$GITHUB_USER.github.io/$GITHUB_REPO/merged.csv"

if [ $? -ne 0 ]; then
    rm -f merged-old.csv
    touch merged-old.csv
fi
