#!/bin/bash
#
# Get the MSY raw html files, ready for processing with the extractor
#
# TODO
# - be smarter about the pagination - dont just hardcode it

PREFIX="$1"
if [ -n "$PREFIX" ]; then
    PREFIX="$PREFIX/"
fi

set -e

curl_h() {
    local FILE="$1"
    local URL="$2"
    echo "TRY $URL"

    curl \
        -H 'accept-encoding: gzip, deflate, br' \
        -H 'accept-language: en-US,en;q=0.9' \
        -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36' \
        -H 'accept: */*' \
        -H 'referer: https://www.msy.com.au/' \
        --compressed \
        -o "$FILE" \
        "$URL"
}

(cat <<EOF
msyhdd-1.html   https://www.msy.com.au/online/64-hard-drives-ssd?q=Availability-In+stock
msyhdd-2.html   https://www.msy.com.au/online/64-hard-drives-ssd?q=Availability-In+stock&page=2
msyhdd-10.html  https://www.msy.com.au/online/139-flash-drives?q=Availability-In+stock
EOF
) | while read -r name url page; do
    curl_h "$PREFIX$name" "$url" "$page"
    sleep 10s
done
