---
name: CI

on:
  push:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
    scrape:
        name: make test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo make build-depends

            - name: Test environment
              run: |
                chromium --version
                chromedriver --version

            - name: Run scraper
              run: |
                Xvfb :5 &
                export DISPLAY=:5
                make test

            - name: Arrange deploy files
              run: |
                mkdir deploy
                mv *.csv deploy
                mv tmp deploy

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: deploy
